image: python:bullseye

include:
  - project: 'ResComp/gitlab-ci-includes'
    file:
      - ssh.yml

.deploy:
  script:
    - sed "s/YOUR_DB_HOST/$DB_HOST/" .env_template |
        sed "s/YOUR_DB_USER/$DB_USER/" |
        sed "s/YOUR_DB_NAME/$DB_NAME/" |
        sed "s/YOUR_FILESPACE/$FILESPACE_PATH/" |
        sed "s/YOUR_DB_PASS/$DB_PASS/" > .env
    - echo SESSION_COOKIE_SECURE=True >> .env
    - scp -o stricthostkeychecking=no -r * .env $SSH_USER@$SSH_SERVER:$DEPLOY_PATH
    - ssh -o stricthostkeychecking=no $SSH_USER@$SSH_SERVER "cd $DEPLOY_PATH && ./setup.sh"

stages:
  - test
  - deploy-test
  - deploy-prod

test:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest

deploy-test:
  stage: deploy-test
  variables:
    SSH_USER: $TEST_SSH_USER
    SSH_SERVER: $TEST_SSH_SERVER
    SSH_KEY: "$TEST_SSH_KEY"
    SSH_PASSPHRASE: "$TEST_SSH_PASS"
    DEPLOY_PATH: $TEST_DEPLOY_PATH
    FILESPACE_PATH: $TEST_FILESPACE_PATH
    DB_HOST: $TEST_DB_HOST
    DB_USER: $TEST_DB_USER
    DB_NAME: $TEST_DB_NAME
    DB_PASS: "$TEST_DB_PASS"
  before_script:
    - !reference [.ssh_with_passphrase, before_script]
  script:
    - !reference [.deploy, script]
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

deploy-prod:
  stage: deploy-prod
  variables:
    SSH_USER: $PROD_SSH_USER
    SSH_SERVER: $PROD_SSH_SERVER
    SSH_KEY: "$PROD_SSH_KEY"
    SSH_PASSPHRASE: "$PROD_SSH_PASS"
    DEPLOY_PATH: $PROD_DEPLOY_PATH
    FILESPACE_PATH: $PROD_FILESPACE_PATH
    DB_HOST: $PROD_DB_HOST
    DB_USER: $PROD_DB_USER
    DB_NAME: $PROD_DB_NAME
    DB_PASS: "$PROD_DB_PASS"
  before_script:
    - !reference [.ssh_with_passphrase, before_script]
  script:
    - sed -i 's/DEV_STADOLPHINACOUSTICS/PROD_STADOLPHINACOUSTICS/' .env_template
    - sed -i 's/DevelopmentConfig/ProductionConfig/' ./ocean/wsgi.py
    - !reference [.deploy, script]
  rules:
    - if: '$CI_COMMIT_TAG != null'